services:
  db:
    container_name: postgresdb
    image: postgres:17
    environment:
      POSTGRES_DB: apibank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: api_bank
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/apibank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres_data: